[workspace]
authors = ["Denis Sergeev <dennis.sergeev@gmail.com>"]
channels = ["conda-forge"]
name = "cv"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.3,<3.14"
matplotlib = ">=3.10.1,<4"
numpy = ">=2.2.4,<3"
pandas = ">=2.2.3,<3"
requests = ">=2.32.3,<3"
